### ISSUE TITLE
Departure times, Route 75 towards city

### ISSUE THREAD

**Issue by Feurmann** [andybotting/tramhunter#15]
Instead of showing the time to departure as usual, the stops on Route 75 (towards the city) are showing what look like the departure times from Camberwell Depot. Examples: all times begin with "Camberwell Depot" and then give times like Sat 12.22 am, Sat 12.41 am, Sat 12.55 am. Refreshing the screen and removing the stop from Favourites then reinstating it doesn't do anything. I looked at a few stops on the same route going towards Vermont South and they don't seem to be affected; just the city bound ones. Thanks!

**Comment by andybotting** [comment]
The Tram Tracker app shows the same, so looks like its not a fault of Tram Hunter.

Can you give me the TramTracker ID of the stop you're interested in?

**Comment by Feurmann** [comment]
Stop 60, Millicent Street.

**Comment by andybotting** [comment]
The Stop ID is 1960. 

Tram Tracker shows it as Route 75d:
http://tramtracker.com.au/pid.html#pid-page?tid=1960

If you're sure this is a mistake, then you should take it up with Yarra Trams. Looks like it's an issue with their data.

cheers,
Andy

**Comment by Feurmann** [comment]
Thanks Andy. (The stop number shows as a two digit number in TramHunter, but useful to have the full ID.) It is definitely a mistake as the data displays differently to how it used to, and how it displays on the other stops for the same route going in the other direction. So I will take it up with Yarra Trams.

Regards
Guy
