### ISSUE TITLE
More tram interval

### ISSUE THREAD

**Issue by jonech** [andybotting/tramhunter#16]
Not quite sure how the tram api works and get updated, but is there a chance to make the tram stop display more trams like within 1 or 2 hours? So that the user can plan their day ahead earlier.

**Comment by andybotting** [comment]
Yeah, you're spot on - it's the API at play here. We're just using the simple 'get next trams' API query. Anything else would move away from real-time to timetable data and would then require smarts to marry the two up, which I think might be more effort than it's worth.
